Better welcome message
mssiegel/frempco-client pull request #107
Opened 2022-03-27 20:18 UTC by karlrez

Closes #97 

Added a box to include the welcome message when a student joins a classroom:

![image](https://user-images.githubusercontent.com/47090434/160299116-40fba126-ac5a-4d65-910d-ec73c22ae8e0.png)

When student gets removed:
![image](https://user-images.githubusercontent.com/47090434/160299074-8d8faab8-9a7e-4ffe-9812-fd2755f046b8.png)

2022-03-28 02:45 UTC, karlrez commented
Changed the colors in the last commit (same background color as the chatbox):

![image](https://user-images.githubusercontent.com/47090434/160317783-1aafe679-7643-4f28-8f00-5d3395b3e340.png)

2022-03-29 02:46 UTC, mssiegel requested changes
I absolutely love the color choices!! Seeing the chatbox lookalike sends a shiver through my body. My adrenaline soars as I start imagining the chat I'm about to enter. Using the chatbox colors and shape is BRILLIANT and brings the student experience to a WHOLE NEW LEVEL!!!

This code is clean and I like that the `WelcomeMessage` its own component.  I left some comments about minor things like renaming variables.

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.css.tsx
> +  padding: 70px 0;
I think the code is cleaner to read when just using padding top and bottom.  Setting the horizontal padding to 0 can confuse whoever is reading the code as padding defaults to 0.
```suggestion
  padding-top: 70px;
  padding-bottom: 70px;
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.css.tsx
> +const unpairedMessageContainer = css`
We should be consistent with our naming. Let's use the same variable name as the filename. 
```suggestion
const welcomeMessageContainer = css`
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.css.tsx
> +const unpairedMessageCSS = {
For consistency, lets use the same variable name as the fiename.
```suggestion
const welcomeMessageCSS = {
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.tsx
> +import unpairedMessageCSS from './WelcomeMessage.css';
Renaming this variable name as per previous comments
```suggestion
import welcomeMessageCSS from './WelcomeMessage.css';
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.tsx
> +            Your teacher has removed you from the classroom.
```suggestion
            Your teacher removed you from the classroom.
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.tsx
> +            Please return to the Frempco <Link href='/'>homepage</Link>
```suggestion
            Please return to the <Link href='/'>homepage</Link>
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.tsx
> +
Lets use the `Link` from our shared components folder
```suggestion
import { Box, Typography } from '@mui/material';

import Link from '@components/shared/Link';
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/index.tsx
> +            removed={removedFromClass}
I'd prefer we keep the original variable names. They feel more descriptive to me. 
```suggestion
            classroomName={classroomName}
            removedFromClass={removedFromClass}
```

2022-03-29 02:46 UTC, mssiegel commented on src/components/pages/StudentsPage/WelcomeMessage.css.tsx
> +  border: 1px solid white;
This border  is so small I didn't notice it. We can delete it. 
```suggestion
```

2022-03-29 03:58 UTC, karlrez commented
Wow appreciate the comments!! Updated as per your suggestions

2022-03-29 12:08 UTC, mssiegel approved these changes
Looks great! Good to merge!

2022-03-29 15:58 UTC, merged