Improve teachers flexibility when matching up students for #116
mssiegel/frempco-client pull request #119
Opened 2022-04-06 04:13 UTC by karlrez

Resolves #116 

Added "Pair up" button, color for every other row, and modified text in "Pair up all students" button.
**Test plan:** Did a few test runs with 6 students, lots of pairing, unpairing, and shuffling, so far works for me. 

![image](https://user-images.githubusercontent.com/47090434/161893675-d164c17f-6663-47ca-94a1-c1247cf8609a.png)

2022-04-07 15:18 UTC, mssiegel requested changes
I was really curious how we'd divide up the button to go on the right and this Grid system works really well! Great work.  I left a few minor comments to be addressed.

2022-04-07 15:18 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +                <Box>
I think we can remove this Box that is wrapping it

2022-04-07 15:18 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +                <Box>
I think we can remove this Box that is wrapping it

2022-04-07 15:18 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +                {pair[1] !== undefined && (
We can remove the `!== undefined` and just check the value.  Also, I feel this `&&` check should be with the Grid item that wraps this button.

2022-04-08 22:27 UTC, karlrez commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +          }, [])
Yes! Using the chunk method is a much simplier way of accomplishing this.

2022-04-10 02:14 UTC, mssiegel approved these changes
Looks great to me!

2022-04-12 15:07 UTC, merged