Closes #51
mssiegel/frempco-client pull request #56
Opened 2022-03-01 13:31 UTC by zachlankton

Closes #51

2022-03-01 13:46 UTC, zachlankton commented on pages/student/classroom/[classroomName].tsx
> +  }, [classroomName, studentName]);
This is where the bulk of the magic happens.  The rest of the code changes are just the move from the index page to the student classroom page.

2022-03-01 13:46 UTC, zachlankton commented on src/utils/classrooms.tsx
> +  student?: string;
Needed to add an optional student prop to pass the student name into the Students Page

2022-03-01 13:46 UTC, zachlankton commented on pages/student/classroom/[classroomName].tsx
> +      )}
Cosmetic Change:
Only showing the `StudentsPage` component if they are in a real class room and the modal is not open.  Without this the user sees the Hello message with `Hello !` and `classroom: setupClassroom` which just doesn't look very good.

2022-03-01 13:46 UTC, zachlankton commented on pages/student/classroom/[classroomName].tsx
>      paths,
I put this here instead of in the utility function so that it only affects this page.

2022-03-02 03:38 UTC, mssiegel requested changes
Moving the modal to the classroom page works, but I think its technically overly complex. 

I feel storing global app info should be easy.  The Socket context wouldn't be used to do so.  Instead a new UserContext would be added to store the user info.   

To make this work the UserProvider would be used in Frempco's [_app.tsx](https://github.com/mssiegel/frempco-client/blob/main/pages/_app.tsx) I feel adding a UserProvider would be just a few lines of code. 

For example see this [RootProvider ](https://github.com/hatchways/team-bluejay/blob/dev/client/src/contexts/RootProvider.js )from my Hatchways project. The comment in that file is very important!!! SocketProvider would need to wrap the UserProvider.  This is because the Socket needs to be instantiated first so that the inner UserProvider can use context from the outermost SocketProvider. 

  The RootProvider then wrapped the whole [App](https://github.com/hatchways/team-bluejay/blob/dev/client/src/App.js).

2022-03-02 12:21 UTC, zachlankton commented
No Problem, I actually don't mind either way and wasn't sure which way you would prefer.  I have created an alternative PR #58 that uses a new UserContext.

Moving the Modal nets less added code overall (Mostly just moving code):
![MoveModalAddSub](https://user-images.githubusercontent.com/2927894/156360056-382d8573-018a-419e-8a45-1a24ee97a044.PNG)


While Adding a UserContext is mostly all code addition:
![ContextAddSub](https://user-images.githubusercontent.com/2927894/156360217-6c30c16e-d15d-44d3-9d7f-9c5524b0458e.PNG)

I can definitely see the value having moved the bulk of the complexity into UserContext and leaving the pages and components lean.  I am comfortable with either solution.  Let me know which one you prefer and we can Merge that PR and close the other.

2022-03-03 11:59 UTC, zachlankton commented
Closing this pull request in favor of #58

2022-03-03 11:59 UTC, closed without merging