Closes #54 Ability to Remove Student From Classroom
mssiegel/frempco-client pull request #71
Opened 2022-03-08 01:35 UTC by zachlankton

Closes #54 Ability to Remove Student From Classroom

2022-03-09 14:35 UTC, mssiegel requested changes
While the current version works, I feel teachers might forget they can click a student's name to push them down.  Ideally, I think something like this would be more user friendly: 
![image](https://user-images.githubusercontent.com/29524485/157462271-08a458b8-d4eb-46d7-b337-688f8bca0b5e.png)
The Material UI List component is holding us hostage. We can't build a user friendly design if we use it. We'll need to replace it with our own customized component.   But I think doing so should be its own separate PR that just replaces the List. 
Once thats done, we could after make a new PR with the button to remove student from classroom.
Zach what do you think?

2022-03-09 14:35 UTC, mssiegel commented on src/components/pages/StudentsPage/index.tsx
> +        {removedFromClass && <>You have been removed from the classroom.</>}
```suggestion
        {removedFromClass && <>Your teacher has removed you from the classroom.</>}
```
```suggestion
        {removedFromClass && <>You have been removed from the classroom.</>}
```

2022-03-09 14:35 UTC, mssiegel commented on src/components/pages/StudentsPage/index.tsx
> +        {removedFromClass && <>You have been removed from the classroom.</>}
Convert to a terniary operator. Also "your teacher has removed you..."
```suggestion
        {removedFromClass ? 
          (Your teacher has removed you from the classroom) :
          (Hello {name}! Welcome to your classroom: {classroomName})
         }
```

2022-03-09 14:35 UTC, mssiegel commented on src/components/pages/StudentsPage/index.tsx
> +        {removedFromClass && <>You have been removed from the classroom.</>}
Convert to a terniary operator. Also "your teacher has removed you..."
```suggestion
        {removedFromClass ? 
          (Your teacher has removed you from the classroom) :
          (Hello {name}! Welcome to your classroom: {classroomName})
         }
```

2022-03-09 15:54 UTC, zachlankton commented
> While the current version works, I feel teachers might forget they can click a student's name to push them down. Ideally, I think something like this would be more user friendly: ![image](https://user-images.githubusercontent.com/29524485/157462271-08a458b8-d4eb-46d7-b337-688f8bca0b5e.png) The Material UI List component is holding us hostage. We can't build a user friendly design if we use it. We'll need to replace it with our own customized component. But I think doing so should be its own separate PR that just replaces the List. Once thats done, we could after make a new PR with the button to remove student from classroom. Zach what do you think?

I completely agree, however I would like to merge this (after making updates per the code review) as the ability to remove students who join with a silly name was requested by Ariella, and this gives her the ability to do that.

I believe creating a custom list component and refactoring this code to use it will not be a problem at all.

2022-03-11 02:17 UTC, mssiegel approved these changes
This is phenomenal! Thanks for making the `UnpairedStudentsItem` and for making the hover over the "X" look so good!
I left some minor comments to be addressed. Once done go ahead and merge.

I also left some higher-level questions of `p` vs `padding`, instantiating react components, and destructuring props.  We should set a consistent standard. I'd love your input on this but I don't think its something better discussed in a conversation than in text comments. We should setup a video call next week for it.

2022-03-11 02:17 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +          inset
We can remove `inset`. it now has no effect because of the `paddingLeft: 3`
```suggestion
```

2022-03-11 02:47 UTC, zachlankton commented on src/components/pages/StudentsPage/index.tsx
> +        )}
Ah, quotes worked much better, when I did it with parentheses in your first suggestion prettier reformatted it to the current code.

2022-03-11 02:50 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +            edge='end'
Will go ahead and remove for now.

2022-03-11 02:55 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +              }}
Honestly, this is a personal pet peeve.  I dislike the redundancy of `student={student}` etc...  So unfortunately this is a habit of mine in other code bases.  I don't mind being consistent with the current code base, you just might have to call me out on this once in a while. 😉

2022-03-11 03:04 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +        sx={{ margin: 0, padding: 0 }}
Either one, I'll get better at the consistency thing with time in this code base. I'll use the shortcut as I see that is what is currently used in the code base.

2022-03-11 03:04 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +              }}
Hahahaha awesome!  Yeah, I have no idea why I started doing the redudancy but now its a habit of mine hahaha

2022-03-11 03:04 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +export default function UnpairedStudentItem({ params }) {
Will do

2022-03-11 03:05 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +          inset
Will do!

2022-03-11 03:07 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +  }
Will Do!

2022-03-11 03:08 UTC, mssiegel commented on src/components/pages/TeachersPage/UnpairedStudentItem.tsx
> +        sx={{ margin: 0, padding: 0 }}
Thanks man!!

2022-03-11 03:15 UTC, zachlankton commented on src/components/pages/TeachersPage/UnpairedStudentsList.tsx
> +              }}
It's not just you, everybody does it that way. I'm the outcast on this one. :-)

2022-03-11 03:21 UTC, merged